apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KB54crUewJqjii2U3nE14T70J25+d/7Mkc6gGqEHk7+NER/i,iv:sBJQ6to7/zc+kaYxV+KQvfmfmf6ggi9PAKZcd23PRGw=,tag:9nDqqdG4EoyQAV6osdkBUg==,type:str]
    credentials.json: ENC[AES256_GCM,data:5hZ31w7Q3UQoF8+erBfp6cenYK0faU479146bDYCcyi5lRAXPFoJvTWOVfP8ObiY5XZe+PRR6tAQn6UrU4j1w39u6i+10jxWsS9DDaY5zncJ7aIMV4DLT6YW+JsWqNhAJWBQMCzz0r0pEObtfCPTTiXuUgD60KMu+62L7hyvfXYupSz9EvQTUs6yHtZaWzQ2Ntjw9JGs+YYsGdS/G/aCRiDfGizlHVYdlw0UbMbKsWUzEgUT9V9pLunfVWTMv+lbDoSvI3h28SmAnGOR18J7cEA/u/r7hrrvwY+T5C+/zWodA/gbGnft/wq+5Pt+LUS0WGGc5k69bx26rNX5XVtExFC00FOaDNazz0jVmGnUKqhEeKVfBLeEs5gGZ/2vXfUsd8R5F2wrNl+6Fuk8qlSTZnt/3AbuApADnK1N,iv:2Y6vJCjTgCckw3XJmf2gCZgveDC39vtJ8wnS3c9n47E=,tag:VswfC2JB7VMiRWcIFi8TSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqagq9czrne7lc525garv2q4pe932v9x0zwel6v597ejzfjtqnqjj4wq2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOFNRL0gwL0lBZU94WlFE
            ckRHQnoxVGNmZStTaVlpWXAzRmNJNHA4aEhNClpxRFVNV1JZNmNJTEs0S3crTFgy
            clBaY3dOTzBDMWxtdGxGdERZK2tmY1UKLS0tIGsydER3cXZtVGZuYWlOZWxIQVor
            cjRJZ3EzZlJYaWRpMEhkMmRSTWpHWVkKd0TSuqnKqK2uztMRfz+Z3SshNoEolu10
            h6KLYJXTM5ijhH+toY4LBQI7EprrO9E5DHohN8j2AXhivFKnm17Fsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T21:52:23Z"
    mac: ENC[AES256_GCM,data:BsHniSkC75JQIvP3cUEJsuB+BmMEfPI+hBYBZHsiBZoMIrmEwCx7RnykkyE7hj/wDR+UZLkFtxn8v1aWOMyAJ7HDUm/DzNnznCM+pdGCLt1maxxNo7qTsLJMryDeAEdR+vuu68kzZOWBXoHccXJPs15p1ko5Zd0RdgdutfXyEJY=,iv:4eV8s9qwTiIIwrGhkZ4MjOcagPaV4yGJoyrDD3sG5u0=,tag:y/Aj+LX0AtQ2/rr74w14xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
