apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IDovV6WVXWey,iv:CSwz84HYkExnneDdSUyBTCF7jvLnsyw/YMwtY9RwCvM=,tag:ZZf8hYesCYk9x7mq+Yh/YA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:35PAY0EZ2Jo2v6MJVMb3MN8lUOnrkWsfWg==,iv:td9Dewa/OHz55qIkBXIm/It03OJi89utzsfrevp4JQU=,tag:fm3tIJkWObDCpYmZM62Nxw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tGN7VNRURTzqYzWLpAVpXoMorYTISb/vi/9f/BT3UBuyCvey,iv:XSMoTecp51ZqRP8J3S/Q6MxbNNYLKLLzrqu/HvODYpI=,tag:IxHczeQFGoKrpwdHWf5MLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqagq9czrne7lc525garv2q4pe932v9x0zwel6v597ejzfjtqnqjj4wq2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWpZc3MzL1doRStvOGc1
            alMyRXBNTVJCc29LMFR0aERYQUVvVUFrU2gwCnNZdnNhTXF0MWRhclVDSktPNUJU
            MlhBT0N6eWNmekJuS3ZGd3pNQnJQMjAKLS0tIEhPMldtUlppRVhaWml3SXhja21p
            UjZRVTFZWWRUN1FwKy9CblVsYzl2d2sKkBoMnQNe1RvCfJEFia4bo4yJ8kHzChbs
            KmyKkyYMLd/lX1BuAS8zo3wNMrTKHxjCV+7Yk9uOejKsYz4En3JRMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T23:11:25Z"
    mac: ENC[AES256_GCM,data:VuNq4nP0ev6I9bwErfR4oxTGxDnjZ7B4cx/Y89oxnslSFDOeHBJdVZtJ10q/lnyLSiy0fA2oLQZNCAsj+CocS+T9MzwUfk/xftCvlwqDgNjKrPOJtf0RP9+GSutPkqr4ogR9KKaI8fIJ0qJlVYMPccrXz+a4MhmbW5R+0Ktmt6s=,iv:A/Gvzs4GXTPtfCilNQoLU28nvsZ2PXlUOZLqk/49rrk=,tag:/sHQCvYC/pEmhC9LHT5hRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
