apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:zq+kBsCDQl/D7GqN+wcarZrUozwjHsRC24cOx9wcwmHYBcp3x4i7/A==,iv:WoRVzvQKyUsF3M7lIkiGEu/64J1G1uWMnV9+IlnQrHE=,tag:0zwsKMai9E/sprqTnmHrog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dzqagq9czrne7lc525garv2q4pe932v9x0zwel6v597ejzfjtqnqjj4wq2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTTE5K20xMkZRZ01kNmhO
            bHNRY2dPQjRMM1lTM3hxcjdIM0ZKZ3NHM2owCnpZa085a1d1Q3g3UWwvVDJQYU9Z
            Ymw2VW5PWHJIVyt0N3lxcUN0ZWd2T1EKLS0tIEJNRm1sUHdvZXNsUmhjVEJaaStU
            TjhZcWVwaU4rQ0gvVHpSamZkMHZaZHMKwxsPSwjvkMnr3jDdjrgEr2gxvJoqcXtR
            y6vFC9/1Lum6iZ8K1U6IXpClsVEaOwCVl6qK+LmP5wA0iEF5ntSWkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T23:11:25Z"
    mac: ENC[AES256_GCM,data:6LQgDVYREX07WtzSxlzupWNqEwQK4QSEw+0j93jXt9Llr0M88G0aEAeY4w2veSmg3AXE/90x775RvwcY2PdxgeCAohazoveiPovPqYPjQoGMCLADFveWDHL1pVKs7/nXz2NSsHdjtfikJlvGz7jOl8qHG8UsN8zI6jxuaMLBfL8=,iv:gR/XLflHrpoVv3eYgFSYV5RatAQLdQ3HGiI0trPw9f4=,tag:lJxMbyXV3Me0ZsSAU+KfQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
